### ISSUE TITLE
Replace fluidSize mixin instances with mobile-first CSS

### ISSUE THREAD

**Issue by EthanThatOneKid** [acmcsufoss/acmcsuf.com#13]
A SCSS mixin is used in many Svelte files across the project. I used it to help with implementing the design, but they really should all be converted into mobile-first CSS solutions for better maintainability and structure.

Example:

```scss
@include fluidSize(18, 48, $propName: "font-size");
```

Here is an example of fluidSize being used. 18 is the value in pixels for the mobile design and 48 is the value in pixels for the desktop design. `"font-size"` is the CSS property that is being targeted. A mobile-first CSS alternative is more long-winded, but will be more maintainable over time.

```css
p {
  font-size: 18px;
}

@media screen and (min-width: $breakpoint) {
  p {
    font-size: 48px;
   }
}
```

> 💡 Use your best judgement when messing around with the CSS.

**Comment by diamondburned** [comment]
Is falling back to `@media` for `font-size` a really good idea? Perhaps `em` could be used as a relative font size instead, combined with the [viewport meta tag](https://developer.mozilla.org/en-US/docs/Web/HTML/Viewport_meta_tag), which wouldn't need edge cases with `@media`.

**Comment by EthanThatOneKid** [comment]
I agree that the `font-size` property should use `em` units 👍.

The above code is just an example for converting from the `fluidSize` mixin in general. In the codebase, there are instances of `fluidSize` where this conversion would make sense.
For example, when the property is `width` instead of `font-size`.

**Comment by diamondburned** [comment]
It seems like a CSS `var` can't be used on a `@media` like so:

```css
  @media screen and (min-width: var(--desktop-breakpoint)) { /* <-- does not work */
	.screen-wyd div {
	  padding-left: var(--max-padding);
	  padding-right: var(--max-padding);
	  padding-bottom: var(--max-p-font-size);
	}

	.screen-wyd p,
	.screen-wyd h2 {
	  font-size: var(--max-h-font-size-med);
	  padding-bottom: var(--max-p-font-size);
	};
  };
```

I suppose we still have to keep that specific part SCSS, though I'm not sure if I should still convert all other variables to CSS.
