### ISSUE TITLE
Create hero.svelte for the hero 😎

### ISSUE THREAD

**Issue by EthanThatOneKid** [acmcsufoss/acmcsuf.com#14]
Create a file, `src/components/sections/hero.svelte`, to store the hero section of the website.

Here is the markup that is currently being used as the hero:

```html
<section class="info-screen screen-hero">
  <div>
    <h1 class="intro-header">
      <span class="headers">
        we are the largest tech
        <br />
        community at
      </span>
      <span class="brand-em brand-blue">CSUF</span>
    </h1>
    <CallToAction text="join us today!" />
  </div>
</section>
```

And here is the current SCSS associated with it:

```scss
  .screen-hero {
    background: 90% 50% no-repeat url(../assets/badges/acm-blank.svg);
    div {
      @include fluidSize(10, 128, $propName: "margin-left");
      padding-top: 221px;
      min-width: "max-content";
      h1 {
        @include fluidSize($minHFontSize, $maxHFontSize);
        @include fluidSize(
          $minPFontSize,
          $maxPFontSize,
          $propName: "padding-bottom"
        );
        font-weight: bold;
      }
    }
  }
```
