### ISSUE TITLE
Create `why-join.svelte` section 😮

### ISSUE THREAD

**Issue by EthanThatOneKid** [acmcsufoss/acmcsuf.com#15]
Create a file, `src/components/sections/why-join.svelte`, to store the *why should you join acm* section of the website.

Here is the markup that is currently being used:

```html
<section class="info-screen screen-why-join">
  <div>
    <h2><span class="headers">why should students join acm?</span></h2>
    <p>
      <span class="headers">acm</span><span class="brand-blue brand-em"
        >CSUF</span
      >
      strives to be a community that encourages growth, friendship, and personal/technical
      development to prepare people for challenges in their personal lives, school
      lives, and industry lives.
    </p>
  </div>
</section>
```

And here is the current SCSS associated with it:

```scss
  .screen-why-join {
    background: 10% 50% no-repeat url(../assets/badges/acm-blank.svg);
    div {
      @include fluidSize(10, 128, $propName: "padding-right");
      padding-top: 333px;
      h2 {
        @include fluidSize($minHFontSize, $maxHFontSizeMed);
        @include fluidSize(10, 32, $propName: "padding-bottom");
        font-weight: bold;
        text-align: right;
        margin: 0;
      }
      p {
        @include fluidSize($minPFontSize, $maxPFontSize);
        @include fluidSize(150, 1014, $propName: "width");
        text-align: right;
        float: right;
        margin: 0;
      }
    }
  }
```
