### ISSUE TITLE
Meeting (10/15/21) ⎼ First Meeting

### ISSUE THREAD

**Issue by EthanThatOneKid** [acmcsufoss/acmcsuf.com#193]
```yaml
started: 7:00 PM
ended: 7:30 PM
slides: https://docs.google.com/presentation/d/1XmEEYeQHtryt2998wSv0s4YUuN9nYu88NTgnf1E8ezw/edit
```

This was the first official meeting of the Fall 2021 semester sprint.
