### ISSUE TITLE
Meeting (10/22/21) ⎼ Sesh A

### ISSUE THREAD

**Issue by EthanThatOneKid** [acmcsufoss/acmcsuf.com#194]
```yaml
started: 7:00 PM
ended: 7:30 PM
slides: https://docs.google.com/presentation/d/1Oa0UQ4mEBfJT9UJTNi9mJUhzUK4mHdTUeptd6ZV-ScE/edit
```
