### ISSUE TITLE
Meeting (10/29/21) ⎼ Sesh B

### ISSUE THREAD

**Issue by EthanThatOneKid** [acmcsufoss/acmcsuf.com#195]
```yaml
started: 5:00 PM
ended: 6:30 PM
slides: https://docs.google.com/presentation/d/1sQ_M-RKKFCn2-Npr3WidSWDjDK2naWJ_SVoX3tm10z0/edit
```
