### ISSUE TITLE
Meeting (11/5/21) ⎼ Sesh C

### ISSUE THREAD

**Issue by EthanThatOneKid** [acmcsufoss/acmcsuf.com#196]
```yaml
started: 5:00 PM
ended: 6:30 PM
slides: https://docs.google.com/presentation/d/1OS0OJ7AWqfiiX0S1WQWAN2xRtp_xL77hmWlyjc4OiB8/edit
```

- Created #192.
