### ISSUE TITLE
Create `acm-select.svelte` ▶

### ISSUE THREAD

**Issue by EthanThatOneKid** [acmcsufoss/acmcsuf.com#24]
Create a file, `/src/components/ui/acm-select.svelte` that contains the drop-down select component on the *about* page.

Here is the markup that has already been created:

```html
<select name="school-year" bind:value="{currentSchoolYear}">
  {#each Object.keys(officers) as schoolYear (schoolYear)}
    <option value="{schoolYear}">{schoolYear}</option>
  {/each}
</select>
```

This component will need one properties and one event type. The property will be `export let datalist: string[];` (which will take the place of `students` in the above code). The event will be called `"change"`. Here is some [info on making an event dispatcher in Svelte](https://svelte.dev/docs#createEventDispatcher).

Also, here is the current associated styling:

```scss
select {
  background-color: $acmDark;
  padding: 1em;
  color: $acmLight;
  font-family: "Poppins", sans-serif;
  font-weight: bold;
  border-radius: 25px;

  option {
    background-color: $acmDark;
    color: $acmLight;
    border-radius: 25px;
  }
}
```

This styling was written with SCSS, but this component will be rewritten in CSS. To convert to CSS, replace `$acmDark` with `var(--acm-dark)` and replace `$acmLight` with `var(--acm-light)`.
