### ISSUE TITLE
Plaintext blogpost metadata displays timestamp of last updated instead of created

### ISSUE THREAD

**Issue by EthanThatOneKid** [acmcsufoss/acmcsuf.com#275]
### What happened?

I would prefer to see the timestamp at which the post was initially created instead of when it was last edited.

## Where?

![image](https://user-images.githubusercontent.com/31261035/150912143-88b9eac3-8ac3-48a4-a6f7-99afead98732.png)

_text from [screenshot](https://acm-csuf-site-git-ethanthatonekid-rnd-re-156a87-ethanthatonekid.vercel.app/blog/262.txt>)_:

```yaml
id: 262
title: "What's new in acmcsuf.com v2.0?"
author: "EthanThatOneKid (https://github.com/EthanThatOneKid)"
labels: []
date: "2022-01-25T01:57:50.000Z"
```

In the screenshot above, the timestamp shown is from the last time the GitHub discussion was updated, not the time it was created.
